on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main

jobs:
  scan-go-js:
    strategy:
      fail-fast: false
      matrix:
        version: [2.14.4, 2.14.5, 2.14.6, 2.15.0, 2.15.1, 2.15.2, 2.15.3]
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 16.19.0
    - run: |
        which node
        node --version
        echo $PATH
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: go,python
        tools: https://github.com/github/codeql-action/releases/download/codeql-bundle-v${{ matrix.version }}/codeql-bundle-linux64.tar.gz
    - name: Run codeql database create
      run: |
        mkdir -p /tmp/codeql/db
        /opt/hostedtoolcache/CodeQL/${{ matrix.version }}/x64/codeql/codeql database create --language=go,python --db-cluster --no-run-unnecessary-builds --source-root=. --working-dir=. /tmp/codeql/db
    
